# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-18 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cours_org',
            new_name='course_org',
        ),
    ]
