# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-19 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20180419_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='you_need_know',
            new_name='youneed_know',
        ),
    ]
