# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-20 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20180420_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_org',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
