# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-07 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180406_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default="image/default.png' %}", upload_to='image/%Y/%m'),
        ),
    ]
